repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: end-of-file-fixer
  - id: mixed-line-ending
    exclude: CHANGELOG.md
  - id: trailing-whitespace
  - id: check-yaml
  - id: check-toml
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
  - id: python-check-blanket-noqa
- repo: https://github.com/timothycrosley/isort
  rev: 5.12.0
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: 23.10.1
  hooks:
  - id: black
- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear>=23.1.20
    - flake8-builtins>=2.1.0
    - flake8-comprehensions>=3.10.1
