name: CD

on:
  push:
    tags:
    - v*

jobs:
  publish:
    name: Publish to PyPi
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
        token: ${{ secrets.ADMIN_WRITE_PAT }}
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install flit
      run: |
        pip install flit>=3.9.0
    - name: Build and publish
      run: |
        flit publish --debug
      env:
        FLIT_USERNAME: __token__
        FLIT_PASSWORD: ${{ secrets.PYPI_KEY }}
